language: cpp
sudo: required
dist: xenial
compiler:
- gcc
- clang
os:
- linux
- osx
osx_image: xcode11.6 # OS X 10.15.5
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; fi
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install python3 bison flex libboost-dev libboost-filesystem-dev libboost-system-dev python3 ; fi
- if [ $TRAVIS_OS_NAME == linux ]; then pyenv install 3.5.1 ; pyenv global 3.5.1; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew install python3 bison flex -v -f 2>&1 && brew upgrade boost || true; fi
- if [ $TRAVIS_OS_NAME == osx ]; then curl "https://bootstrap.pypa.io/pip/get-pip.py" | sudo python3; fi

install:
#- sudo pip install --upgrade pip setuptools
#- CC=gcc sudo pip install requests[security]
- if [ $TRAVIS_OS_NAME == osx ]; then sudo pip install tornado; fi
- if [ $TRAVIS_OS_NAME == osx ]; then sudo pip install --user nose; fi
- if [ $TRAVIS_OS_NAME == osx ]; then sudo pip install pytest --upgrade --ignore-installed six; fi
- if [ $TRAVIS_OS_NAME == linux ]; then sudo pip install pytest; fi
- sudo pip install pyyaml
- sudo pip install enum34
- sudo pip install pyserial
script:
- make all
- pushd erpcgen/test ; py.test ; popd
- python3 test/run_unit_tests.py
