# Copyright (c) 2016, Freescale Semiconductor, Inc.
# Copyright 2016 NXP
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

#
# Generated by erpcgen 1.9.1 on Tue Jun 21 11:28:31 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

