var annotated_dup =
[
    [ "erpc", null, [
      [ "ArbitratedClientManager", "classerpc_1_1_arbitrated_client_manager.html", "classerpc_1_1_arbitrated_client_manager" ],
      [ "BasicCodec", "classerpc_1_1_basic_codec.html", "classerpc_1_1_basic_codec" ],
      [ "BasicCodecFactory", "classerpc_1_1_basic_codec_factory.html", "classerpc_1_1_basic_codec_factory" ],
      [ "ClientManager", "classerpc_1_1_client_manager.html", "classerpc_1_1_client_manager" ],
      [ "RequestContext", "classerpc_1_1_request_context.html", "classerpc_1_1_request_context" ],
      [ "ClientServerCommon", "classerpc_1_1_client_server_common.html", "classerpc_1_1_client_server_common" ],
      [ "Codec", "classerpc_1_1_codec.html", "classerpc_1_1_codec" ],
      [ "CodecFactory", "classerpc_1_1_codec_factory.html", "classerpc_1_1_codec_factory" ],
      [ "Crc16", "classerpc_1_1_crc16.html", "classerpc_1_1_crc16" ],
      [ "FramedTransport", "classerpc_1_1_framed_transport.html", "classerpc_1_1_framed_transport" ],
      [ "ManuallyConstructed", "classerpc_1_1_manually_constructed.html", "classerpc_1_1_manually_constructed" ],
      [ "MessageBuffer", "classerpc_1_1_message_buffer.html", "classerpc_1_1_message_buffer" ],
      [ "Cursor", "classerpc_1_1_cursor.html", "classerpc_1_1_cursor" ],
      [ "MessageBufferFactory", "classerpc_1_1_message_buffer_factory.html", "classerpc_1_1_message_buffer_factory" ],
      [ "MessageLogger", "classerpc_1_1_message_logger.html", "classerpc_1_1_message_logger" ],
      [ "MessageLoggers", "classerpc_1_1_message_loggers.html", "classerpc_1_1_message_loggers" ],
      [ "PrePostAction", "classerpc_1_1_pre_post_action.html", "classerpc_1_1_pre_post_action" ],
      [ "Service", "classerpc_1_1_service.html", "classerpc_1_1_service" ],
      [ "Server", "classerpc_1_1_server.html", "classerpc_1_1_server" ],
      [ "SimpleServer", "classerpc_1_1_simple_server.html", "classerpc_1_1_simple_server" ],
      [ "StaticQueue", "classerpc_1_1_static_queue.html", "classerpc_1_1_static_queue" ],
      [ "Transport", "classerpc_1_1_transport.html", "classerpc_1_1_transport" ],
      [ "TransportFactory", "classerpc_1_1_transport_factory.html", "classerpc_1_1_transport_factory" ],
      [ "TransportArbitrator", "classerpc_1_1_transport_arbitrator.html", "classerpc_1_1_transport_arbitrator" ],
      [ "Thread", "classerpc_1_1_thread.html", "classerpc_1_1_thread" ],
      [ "Mutex", "classerpc_1_1_mutex.html", "classerpc_1_1_mutex" ],
      [ "Semaphore", "classerpc_1_1_semaphore.html", "classerpc_1_1_semaphore" ],
      [ "DspiMasterTransport", "classerpc_1_1_dspi_master_transport.html", "classerpc_1_1_dspi_master_transport" ],
      [ "DspiSlaveTransport", "classerpc_1_1_dspi_slave_transport.html", "classerpc_1_1_dspi_slave_transport" ],
      [ "I2cSlaveTransport", "classerpc_1_1_i2c_slave_transport.html", "classerpc_1_1_i2c_slave_transport" ],
      [ "InterThreadBufferTransport", "classerpc_1_1_inter_thread_buffer_transport.html", "classerpc_1_1_inter_thread_buffer_transport" ],
      [ "LPI2cSlaveTransport", "classerpc_1_1_l_p_i2c_slave_transport.html", "classerpc_1_1_l_p_i2c_slave_transport" ],
      [ "LPSpiSlaveTransport", "classerpc_1_1_l_p_spi_slave_transport.html", "classerpc_1_1_l_p_spi_slave_transport" ],
      [ "MBOXTransport", "classerpc_1_1_m_b_o_x_transport.html", "classerpc_1_1_m_b_o_x_transport" ],
      [ "MUTransport", "classerpc_1_1_m_u_transport.html", "classerpc_1_1_m_u_transport" ],
      [ "RPMsgLinuxTransport", "classerpc_1_1_r_p_msg_linux_transport.html", "classerpc_1_1_r_p_msg_linux_transport" ],
      [ "RPMsgBase", "classerpc_1_1_r_p_msg_base.html", "classerpc_1_1_r_p_msg_base" ],
      [ "RPMsgRTOSTransport", "classerpc_1_1_r_p_msg_r_t_o_s_transport.html", "classerpc_1_1_r_p_msg_r_t_o_s_transport" ],
      [ "RPMsgTransport", "classerpc_1_1_r_p_msg_transport.html", "classerpc_1_1_r_p_msg_transport" ],
      [ "RPMsgTTYRTOSTransport", "classerpc_1_1_r_p_msg_t_t_y_r_t_o_s_transport.html", "classerpc_1_1_r_p_msg_t_t_y_r_t_o_s_transport" ],
      [ "SerialTransport", "classerpc_1_1_serial_transport.html", "classerpc_1_1_serial_transport" ],
      [ "SpiMasterTransport", "classerpc_1_1_spi_master_transport.html", "classerpc_1_1_spi_master_transport" ],
      [ "SpiSlaveTransport", "classerpc_1_1_spi_slave_transport.html", "classerpc_1_1_spi_slave_transport" ],
      [ "SpidevMasterTransport", "classerpc_1_1_spidev_master_transport.html", "classerpc_1_1_spidev_master_transport" ],
      [ "TCPTransport", "classerpc_1_1_t_c_p_transport.html", "classerpc_1_1_t_c_p_transport" ],
      [ "UartTransport", "classerpc_1_1_uart_transport.html", "classerpc_1_1_uart_transport" ],
      [ "UsbCdcTransport", "classerpc_1_1_usb_cdc_transport.html", "classerpc_1_1_usb_cdc_transport" ]
    ] ],
    [ "DynamicMessageBufferFactory", "class_dynamic_message_buffer_factory.html", "class_dynamic_message_buffer_factory" ],
    [ "I2C_CLB_USER_DATA_PTR", "struct_i2_c___c_l_b___u_s_e_r___d_a_t_a.html", "struct_i2_c___c_l_b___u_s_e_r___d_a_t_a" ],
    [ "LPI2C_CLB_USER_DATA_PTR", "struct_l_p_i2_c___c_l_b___u_s_e_r___d_a_t_a.html", "struct_l_p_i2_c___c_l_b___u_s_e_r___d_a_t_a" ],
    [ "RPMsgMessageBufferFactory", "class_r_p_msg_message_buffer_factory.html", "class_r_p_msg_message_buffer_factory" ],
    [ "StaticMessageBufferFactory", "class_static_message_buffer_factory.html", "class_static_message_buffer_factory" ]
];