/** 
 * Generated by erpcgen 1.12.0 on Mon Jan  8 10:25:43 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */
 package io.github.embeddedrpc.erpc.tests.test_arrays.test_unit_test_common.common;


import io.github.embeddedrpc.erpc.tests.test_arrays.test_unit_test_common.common.enums.*;


import java.util.ArrayList;
import java.util.List;

public final class Constants {
        public static final int c_x = 5;

    private Constants() {
    }
}

