/** 
 * Generated by erpcgen 1.12.0 on Mon Jan  8 10:25:43 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */
 package io.github.embeddedrpc.erpc.tests.test_annotations.test_unit_test_common.common;




import io.github.embeddedrpc.erpc.tests.common.myEnum;

import java.util.ArrayList;
import java.util.List;

public final class Constants {

    private Constants() {
    }
}

