/** 
 * Generated by erpcgen 1.11.0 on Fri Oct 20 09:27:26 2023.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */
 package com.nxp.erpc.tests.test_annotations.test_unit_test_common.common;




import com.nxp.erpc.tests.common.myEnum;

import java.util.ArrayList;
import java.util.List;

public final class Constants {

    private Constants() {
    }
}

