/** 
 * Generated by erpcgen 1.12.0 on Mon Oct 30 10:47:32 2023.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */
 package com.nxp.erpc.tests.test_annotations.test_unit_test_common.common;




import com.nxp.erpc.tests.common.myEnum;

import java.util.ArrayList;
import java.util.List;

public final class Constants {

    private Constants() {
    }
}

