/*
 * Copyright 2018,2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Generated by erpcgen 1.13.0 on Thu Apr 18 09:37:38 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_erpc_two_way_rpc_Core0Interface_client_h_)
#define _c_erpc_two_way_rpc_Core0Interface_client_h_

#include "erpc_two_way_rpc_Core0Interface_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS_CORE0INTERFACE)
#define ERPC_FUNCTIONS_DEFINITIONS_CORE0INTERFACE

typedef void (*getNumberCallback_t)(uint32_t * param1);

/*! @brief Core0Interface identifiers */
enum _Core0Interface_ids
{
    kCore0Interface_service_id = 1,
    kCore0Interface_setGetNumberFunction_id = 1,
    kCore0Interface_getGetNumberFunction_id = 2,
    kCore0Interface_nestedCallGetNumber_id = 3,
    kCore0Interface_getNumberFromCore1_id = 4,
};

/*! Core0 interface */
//! @name Core0Interface
//@{
/*! Sets callback function. To the other side. Implementation on Core1  */
void setGetNumberFunction(const getNumberCallback_t getNumberCallbackParam);

/*! Gets callback function. Implementation on Core1  */
void getGetNumberFunction(getNumberCallback_t * getNumberCallbackParam);

/*! Sets callback function. To the other side. Implementation on Core1  */
void nestedCallGetNumber(const getNumberCallback_t getNumberCallbackParam);

/*! Callback function. Implementation on Core1 */
void getNumberFromCore1(uint32_t * number);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS_CORE0INTERFACE

void initCore0Interface_client(erpc_client_t client);

void deinitCore0Interface_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_erpc_two_way_rpc_Core0Interface_client_h_
