/*
 * Copyright 2018,2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Generated by erpcgen 1.14.0 on Wed May 28 10:34:55 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "erpc_two_way_rpc_Core0Interface_interface.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


using namespace std;
using namespace erpcShim;

Core0Interface_interface::~Core0Interface_interface(void)
{
}
Core0Interface_interface::getNumberCallback_t Core0Interface_interface::_getNumberCallback_t[1] = { &Core0Interface_interface::getNumberFromCore1 };

bool Core0Interface_interface::get_callbackAddress_getNumberCallback_t(uint16_t index, getNumberCallback_t *callback)
{
    bool find;

    if (index<sizeof(_getNumberCallback_t)/sizeof(getNumberCallback_t))
    {
        find = true;
        *callback=Core0Interface_interface::_getNumberCallback_t[index];
    }
    else
    {
        find = false;
    }

    return find;
}

bool Core0Interface_interface::get_callbackIdx_getNumberCallback_t(const getNumberCallback_t *callback, uint16_t &index)
{
    bool find = false;

    for (index = 0; index < sizeof(_getNumberCallback_t)/sizeof(getNumberCallback_t); index++)
    {
        if (Core0Interface_interface::_getNumberCallback_t[index] == *callback)
        {
            find = true;
            break;
        }
    }

    return find;
}
