/*
 * Copyright 2018,2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Generated by erpcgen 1.14.0 on Wed May 28 10:34:55 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_two_way_rpc_Core0Interface_client_hpp_)
#define _erpc_two_way_rpc_Core0Interface_client_hpp_

#include "erpc_two_way_rpc_Core0Interface_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class Core0Interface_client: public Core0Interface_interface
{
    public:
        Core0Interface_client(erpc::ClientManager *manager);

        virtual ~Core0Interface_client();

        /*! Sets callback function. To the other side. Implementation on Core1  */
        virtual void setGetNumberFunction(const getNumberCallback_t getNumberCallbackParam);

        /*! Gets callback function. Implementation on Core1  */
        virtual void getGetNumberFunction(getNumberCallback_t * getNumberCallbackParam);

        /*! Sets callback function. To the other side. Implementation on Core1  */
        virtual void nestedCallGetNumber(const getNumberCallback_t getNumberCallbackParam);

        /*! Callback function. Implementation on Core1 */
        virtual void getNumberFromCore1(uint32_t * number);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _erpc_two_way_rpc_Core0Interface_client_hpp_
