/*
 * Copyright 2018,2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Generated by erpcgen 1.13.0 on Thu Apr 18 09:37:38 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_two_way_rpc_Core1Interface_client_hpp_)
#define _erpc_two_way_rpc_Core1Interface_client_hpp_

#include "erpc_two_way_rpc_Core1Interface_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class Core1Interface_client: public Core1Interface_interface
{
    public:
        Core1Interface_client(erpc::ClientManager *manager);

        virtual ~Core1Interface_client();

        /*! Function for increasing given number by 1. Implementation on Core0 */
        virtual void increaseNumber(uint32_t * number);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _erpc_two_way_rpc_Core1Interface_client_hpp_
