/*
 * Copyright 2018,2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Generated by erpcgen 1.13.0 on Thu Apr 18 09:37:38 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_two_way_rpc_Core0Interface_common_hpp_)
#define _erpc_two_way_rpc_Core0Interface_common_hpp_


#include <cstddef>
#include <cstdint>

#include "erpc_version.h"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_ERPC_TWO_WAY_RPC)
#define ERPC_TYPE_DEFINITIONS_ERPC_TWO_WAY_RPC

#endif // ERPC_TYPE_DEFINITIONS_ERPC_TWO_WAY_RPC


#endif // _erpc_two_way_rpc_Core0Interface_common_hpp_
