/*
 * Copyright 2018,2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Generated by erpcgen 1.14.0 on Wed May 28 10:34:55 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_two_way_rpc_Core0Interface_common_h_)
#define _erpc_two_way_rpc_Core0Interface_common_h_


#if defined(__cplusplus)
extern "C"
{
#endif
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "erpc_version.h"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_ERPC_TWO_WAY_RPC)
#define ERPC_TYPE_DEFINITIONS_ERPC_TWO_WAY_RPC

#endif // ERPC_TYPE_DEFINITIONS_ERPC_TWO_WAY_RPC

#if defined(__cplusplus)
}
#endif

#endif // _erpc_two_way_rpc_Core0Interface_common_h_
