/*
 * Copyright 2018,2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Generated by erpcgen 1.14.0 on Wed May 28 10:34:55 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_two_way_rpc_Core1Interface_interface_hpp_)
#define _erpc_two_way_rpc_Core1Interface_interface_hpp_

#include "erpc_two_way_rpc_Core1Interface_common.hpp"

namespace erpcShim
{


// Abstract base class for Core1Interface
class Core1Interface_interface
{
    public:
        static const uint8_t m_serviceId = 2;
        static const uint8_t m_increaseNumberId = 1;

        virtual ~Core1Interface_interface(void);

        /*! Function for increasing given number by 1. Implementation on Core0 */
        virtual void increaseNumber(uint32_t * number) = 0;
private:
};
} // erpcShim


#endif // _erpc_two_way_rpc_Core1Interface_interface_hpp_
