/** 
 * Generated by erpcgen 1.12.0 on Mon Oct 30 14:04:10 2023.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */ 

package com.nxp.erpc.example.erpc_matrix_multiply.interfaces;




import com.nxp.erpc.auxiliary.Reference;

import java.util.List;

public interface IMatrixMultiplyService {
    int SERVICE_ID = 1;
    int ERPCMATRIXMULTIPLY_ID = 1;

    void erpcMatrixMultiply(int[][] matrix1, int[][] matrix2, Reference<int[][]> result_matrix);
}



