/*!
 * Copyright (c) 2016, Freescale Semiconductor, Inc.
 * Copyright 2016 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/** 
 * Generated by erpcgen 1.12.0 on Mon Jan  8 10:25:43 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */ 

package io.github.embeddedrpc.erpc.tests.test_annotations.test_unit_test_common.interfaces;



import io.github.embeddedrpc.erpc.tests.common.myEnum;

import io.github.embeddedrpc.erpc.auxiliary.Reference;

import java.util.List;

public interface ICommon {
    int SERVICE_ID = 0;
    int QUIT_ID = 1;
    int GETSERVERALLOCATED_ID = 2;

    void quit();
    int getServerAllocated();
}



