/** 
 * Generated by erpcgen 1.13.0 on Mon Apr 22 10:58:07 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */ 

package io.github.embeddedrpc.erpc.example.erpc_matrix_multiply.interfaces;




import io.github.embeddedrpc.erpc.auxiliary.Reference;

import java.util.List;

public interface IMatrixMultiplyService {
    int SERVICE_ID = 1;
    int ERPCMATRIXMULTIPLY_ID = 1;

    void erpcMatrixMultiply(int[][] matrix1, int[][] matrix2, Reference<int[][]> result_matrix);
}



