/*
 * Copyright 2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPUART0_InitPins(void); /* Function assigned for the Cortex-M4F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPUART0_DeinitPins(void); /* Function assigned for the Cortex-M4F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPUART1_InitPins(void); /* Function assigned for the Cortex-M4F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPUART1_DeinitPins(void); /* Function assigned for the Cortex-M4F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPUART2_InitPins(void); /* Function assigned for the Cortex-M4F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPUART2_DeinitPins(void); /* Function assigned for the Cortex-M4F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
