# Copyright 2017 NXP
# All rights reserved.
#
#
# SPDX-License-Identifier: BSD-3-Clause

#
# Generated by erpcgen 1.7.1 on Tue Sep 18 11:22:39 2018.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Constant variable declarations
#This const defines the matrix size. The value has to be the same as the
#Matrix array dimension. Do not forget to re-generate the erpc code once the
#matrix size is changed in the erpc file
matrix_size = 5


