# Copyright 2017 NXP
# All rights reserved.
#
#
# SPDX-License-Identifier: BSD-3-Clause

#
# Generated by erpcgen 1.11.0 on Thu Sep 21 15:02:53 2023.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for MatrixMultiplyService
class IMatrixMultiplyService(object):
    SERVICE_ID = 1
    ERPCMATRIXMULTIPLY_ID = 1

    def erpcMatrixMultiply(self, matrix1, matrix2, result_matrix):
        raise NotImplementedError()


