[package]
name = "rust_matrix_multiply"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erpc_rust = { path = "../erpc_rust"}
clap = { version = "4.5.4", features = ["derive"] }