/** 
 * Generated by erpcgen 1.14.0 on Wed May 28 10:34:53 2025.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */
 package io.github.embeddedrpc.erpc.example.erpc_matrix_multiply.common;





import java.util.ArrayList;
import java.util.List;

public final class Constants {
    /*! This const defines the matrix size. The value has to be the same as the
    Matrix array dimension. Do not forget to re-generate the erpc code once the
    matrix size is changed in the erpc file */
    public static final int matrix_size = 5;

    private Constants() {
    }
}

