#
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#

CONFIG_PRINTK=y

# Compiler
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=8192

# eRPC
CONFIG_ERPC=y
CONFIG_ERPC_TRANSPORT_IPC_SERVICE=y

# RPMSG Lite
CONFIG_RL_API_HAS_ZEROCOPY=y
CONFIG_RL_USE_STATIC_API=y

CONFIG_TIMESLICE_SIZE=1

CONFIG_STDOUT_CONSOLE=n

# CONFIG_INIT_STACKS=y
# CONFIG_NO_OPTIMIZATIONS=y
# CONFIG_DEBUG_THREAD_INFO=y
# CONFIG_THREAD_STACK_INFO=y
