/** 
 * Generated by erpcgen 1.12.0 on Mon Oct 30 14:04:10 2023.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */
 package com.nxp.erpc.example.erpc_matrix_multiply.common;





import java.util.ArrayList;
import java.util.List;

public final class Constants {
    /*! This const defines the matrix size. The value has to be the same as the
    Matrix array dimension. Do not forget to re-generate the erpc code once the
    matrix size is changed in the erpc file */
    public static final int matrix_size = 5;

    private Constants() {
    }
}

