/**
 * Generated by erpcgen 1.11.0 on Tue Aug 29 14:02:14 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */
package com.nxp.erpc.example.erpc_matrix_multiply.common;




import java.util.ArrayList;
import java.util.List;

public final class Constants {
    /*! This const defines the matrix size. The value has to be the same as the
    Matrix array dimension. Do not forget to re-generate the erpc code once the
    matrix size is changed in the erpc file */
    public static final Integer matrix_size = 5;

    private Constants() {
    }
}