/*
 * Copyright (c) 2014-2016, Freescale Semiconductor, Inc.
 * Copyright 2016 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Generated by erpcgen 1.13.0 on Thu Apr 18 09:37:38 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_erpc_matrix_multiply_server_h_)
#define _c_erpc_matrix_multiply_server_h_

#include "erpc_matrix_multiply_common.h"

#if defined(__cplusplus)
extern "C"
{
#endif

typedef void * erpc_service_t;

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief MatrixMultiplyService identifiers */
enum _MatrixMultiplyService_ids
{
    kMatrixMultiplyService_service_id = 1,
    kMatrixMultiplyService_erpcMatrixMultiply_id = 1,
};

//! @name MatrixMultiplyService
//@{
void erpcMatrixMultiply(Matrix matrix1, Matrix matrix2, Matrix result_matrix);
//@}


#endif // ERPC_FUNCTIONS_DEFINITIONS

/*! @brief Return MatrixMultiplyService_service service object. */
erpc_service_t create_MatrixMultiplyService_service(void);

/*! @brief Destroy MatrixMultiplyService_service service object. */
void destroy_MatrixMultiplyService_service(erpc_service_t service);


#if defined(__cplusplus)
}
#endif

#endif // _c_erpc_matrix_multiply_server_h_
