/*!
 * Copyright (c) 2014-2015, Freescale Semiconductor, Inc.
 * Copyright 2016 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/** 
 * Generated by erpcgen 1.11.0 on Fri Oct 20 09:27:25 2023.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */

package com.nxp.erpc.tests.test_arrays.test_unit_test_common.common.enums;

import com.nxp.erpc.codec.Codec;

public enum enumColor{
    red(0), 
    green(1), 
    blue(2); 

    private final Integer value;

    enumColor(Integer value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static enumColor get(int value) {
        if (value == 0) {
            return red;
        }
        
        if (value == 1) {
            return green;
        }
        
        if (value == 2) {
            return blue;
        }
        
        return null;
    }

    public static enumColor read(Codec codec) {
        return get(codec.readInt32());
    }

    public void write(Codec codec) {
        codec.writeInt32(this.getValue());
    }
}